---
title: "Getting Used to R, Rstudio, Rmd...."
author: "jsg"
date: "8/21/2020"
output:
  html_notebook
---
Before doing this, review the 1. Welcome and Intro lecture set slides and
the  1_intro_data_lecture.R script in the lectures folder of CUNY-BioStats
github repository

## Getting your first repository
At this point I'm assuming you received the invitation to view the assignment
on github classroom and accepted it. You now have a private repository of these 
files.  In addition to working on R, we'll have you connect your first
project on Rstudio to this repository and work on some basic git skills.

First, open RStudio (on your desktop or cloudserver).  Select file, new
project, Version control.  On the next screen select git. Next you'll need to
enter the url for your repository. Navigate to the web home of your github
repository and for the green **Code** button. Click it, then copy the web url
(or click the copy icon). Input that into the Rstudio **Repository URL**
space.  Then name the project (maybe Assignment 1?).  The **Create
project...** field can be left blank to just save all projects into the main
directory. Alternatively you can click **Browse** and make an Assignments
folder if you want. Whatever you choose, the project will be saved in new
folder in that location using the name you chose.

First, amend the file by replacing the **NAME** spot in the header (top of the
file between the --- markers) with your name.  Now lets make our first commit.
If you look in the upper right windoes, you should see a *Git* tab.  Select it. 
Notice nothing is there. Save the file (using the **Disk** icon or file save).  
Two things will happen.  A file will appear in the Git tab, and it may be covered 
(immediately) by a preview of this file.  You should see your name in the preview!  

Go back to the git tab, click the checkbox next to the files, and select
**Commit**.  You'll need to enter a description. Put "My first commit!" and
press Commit.  

Now you've saved a snapshot of the file to your local Rstudio instance (on
your own machine or server).  If you go the **Git** tab and select **History**
you can select the commit, select any file you made, and actually see the
changes.  We'll only focus on the .Rmd files. That's the one you are writing.
The others are made automatically and produce the html document you see when 
you preview the file.

Now you need to push these changes to the cloud so I can see (and grade) them.
From the **Git** tab, select **Push**.  A window should appear. When it's done
(white text shows) go to your github repository.  You should see notes from 
your commit!  Congratulations!

As you work, use commits to save snapshots of your work in a version control manner, 
and 
pushes to share them with me.  If you get stuck, you can also push your file up
so I can see it and help you fix it (much better than "My code isn't working). 
Then you can actually see "how" I fixed it.  The code will also be useful for 
assessments.

ADD HERE IF YOU CAN @TEACHER IN COMMIT FOR HELP!

Now let's start working in R.  

## R subtleties and functions

1. Let x be defined by


```{r}
 x <- 1:10
```
Try executing this chunk (in R studio, not the webview) by clicking the *Run* button within the chunk or by placing your cursor inside it and pressing *Ctrl+Shift+Enter*.

This will run the code in the Console.  When you save the notebook, an HTML file containing the code and the most recent output will be saved alongside it (click the *Preview* button or press *Ctrl+Shift+K* to preview the HTML file).

The preview shows you a rendered HTML copy of the contents of the editor. Consequently, unlike *Knit*, *Preview* does not run any R code chunks. Instead, the output of the chunk when it was last run in the editor is displayed.


Determine what the “:” does!  Then try to guess the output of these commands

* length(x)
* max(x)
* x[x < 5]
* x^2
* x[ x < 8 & x > 2]

INSERT AN R CHUNK HERE AND RUN EACH OF THESE COMMANDS?  Add a new chunk by clicking the *Insert Chunk* button on the toolbar or by pressing *Ctrl+Alt+I*.



