---
title: "Quiz 4"
author: "jsg"
date: "11/16/2020"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Vaccine effectiveness!

A drug company wants to make sure the vaccine they are developing has similar 
effectiveness for multiple groups.  Out of 10,000 patients, they find the following 
effectivess among groups (labelled with letters to prevent bias!)

 *Outcome*  | Success | Failure
  -| ---     | --
 A |  4600   | 400 
 B |  2750   | 250
 C |  800    | 200
 D |  495    | 505
 
 
1. What is the overall effectiveness of the vaccine?

2. Is there any evidence for differences among groups?

3. How would you relate your findings from question 2 to your answer to question 1? 
Why does it matter (what you would you recommend or do to follow-up)?

Make sure your answers include

* null hypothesis
* alternative hypothesis
* explanation for test you will use
* results from statistical test (including post-hoc tests if needed!)
* clear explanation of how results relate to your stated hypotheses

