---
title: "Binomial"
author: "jsg"
date: "10/21/2020"
output: github_document
---
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# ZOMBIES!

You wake up one morning and find that zombies have taken over your neighborhood (bummer).
One idea is to use biocontrol to reduce zombie attacks. A zombie parasite is 
identified.  Test plots (neighborhoods!) are subjected to one or two releases of 
the parasite at low, medium, or high densities. Past evidence suggests that the 
parasite should infect 70% of the zombies, but some citizens are concerned it won't 
work in New York due to lower temperatures.  In a random sample, 7 of 12 zombies 
are infected with the parasite.  

* What is the observed rate of infection in the sample?

* Is there evidence the parasite infects zombies 
at a different rate in New York?
** If so, why
** If not, how do you explain any discrepancy between the observed rate of infection
and your results?

Make sure your answer includes

* null hypothesis
* alternative hypothesis
* explanation for test you will use
* results from statistical test
* clear explanation of how results relate to your stated hypotheses
* confidence interval for your estimate
