---
title: "Quiz 3"
author: "jsg"
date: "10/21/2020"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# ZOMBIES!

You wake up one morning and find that zombies have taken over your neighborhood (bummer).

Evidence also suggests  that temperature may influence propensity for zombie a
ttacks, with zombies preferring warmer bodies.  Long-term studies suggest that 
average human temperature is 36.57 C.  
Unfortunately, measuring temperatures before/after attacks is hard, so data on 
5 survivors of attacks have been recorded. They were: 36.12, 36.37, 35.7, 36.01, 36.9.  

1. Is there any evidence that temperature influences zombie attacks? 

2. How would knowing the standard deviation of human temperature is 0.42 change
your methods and results?

Make sure your answers include

* null hypothesis
* alternative hypothesis
* explanation for test you will use
* results from statistical test
* clear explanation of how results relate to your stated hypotheses
* confidence interval for your estimate


