6\. Continuous tests 2 populations
================
jsg
10/28/2020

Before doing this, review the **Extending continuous tests to 2
samples** lecture set slides from
<https://sites.google.com/view/biostats/bio-7800178002/week-3> and the
**6\_2\_sample\_continuous tests.R** script in the lecture\_files folder
of the [CUNY-BioStats github
repository](https://github.com/jsgosnell/CUNY-BioStats).

Remember you should

  - add code chunks by clicking the *Insert Chunk* button on the toolbar
    or by pressing *Ctrl+Alt+I* to answer the questions\!
  - **knit** your file to produce a markdown version that you can see\!
  - save your work often
      - **commit** it via git\!
      - **push** updates to github

<!-- end list -->

1.  The following data are human blood clotting times (in minutes) of
    individuals given one of two different drugs.

| Drug B | Drug G |
| ------ | ------ |
| 8.8    | 9.9    |
| 8.4    | 9.0    |
| 7.9    | 11.1   |
| 8.7    | 9.6    |
| 9.1    | 8.7    |
| 9.6    | 10.4   |
|        | 9.5    |

Test the hypothesis that the mean clotting times are equal for the two
groups \* Estimating the variance from the data

``` r
drug_b <- c( 8.8, 8.4, 7.9, 8.7, 9.1, 9.6)
drug_g <- c(9.9, 9.0, 11.1, 9.6, 8.7, 10.4, 9.5)
t.test(drug_b, drug_g)
```

    ## 
    ##  Welch Two Sample t-test
    ## 
    ## data:  drug_b and drug_g
    ## t = -2.5454, df = 10.701, p-value = 0.02774
    ## alternative hypothesis: true difference in means is not equal to 0
    ## 95 percent confidence interval:
    ##  -1.8543048 -0.1314095
    ## sample estimates:
    ## mean of x mean of y 
    ##  8.750000  9.742857

*Using a un-paired t-test, since the experimental units were not matched
and I assumed the means of each group would follow a normal distribution
of unknown variance, I found a test statistics of
t<sub>10.701</sub>=-2.544. This corresponds to a p-value of 0.02. This
p-value is \<.05, so I reject the null hypothesis that the mean clotting
times are the same for the two drugs.*

  - Using rank transform analysis

<!-- end list -->

``` r
wilcox.test(drug_b, drug_g)
```

    ## Warning in wilcox.test.default(drug_b, drug_g): cannot compute exact p-value
    ## with ties

    ## 
    ##  Wilcoxon rank sum test with continuity correction
    ## 
    ## data:  drug_b and drug_g
    ## W = 7, p-value = 0.05313
    ## alternative hypothesis: true location shift is not equal to 0

*Using a un-paired rank-based test, which is appropriate when normality
assumptions can’t be met and I assumed the means of each group would
follow a similar distribution, I found a test statistics of W=7. This
corresponds to a p-value of 0.05. This p-value is \>.05, so I fail to
reject the null hypothesis that the mean clotting times are the same for
the two drugs.*

  - Using a permutation test

<!-- end list -->

``` r
require(coin) #requires data_frame
```

    ## Loading required package: coin

    ## Loading required package: survival

``` r
clotting <- data.frame(drug = c(rep("drug_b", length(drug_b)), rep("drug_g", 
                                                                   length(drug_g))),
                       clotting = c(drug_b, drug_g))
clotting$drug <- factor(clotting$drug)
independence_test(clotting ~ drug, clotting)
```

    ## 
    ##  Asymptotic General Independence Test
    ## 
    ## data:  clotting by drug (drug_b, drug_g)
    ## Z = -2.0726, p-value = 0.03821
    ## alternative hypothesis: two.sided

*Using a permutation test, which is not fully appropriate here due to
small sample sizes (and that also assumes similar distributions for each
group), I found a test statistics of Z=-2.0726.. This corresponds to a
p-value of 0.038. This p-value is \>.05, so I fail to reject the null
hypothesis that the mean clotting times are the same for the two drugs.*

  - Using a bootstrap test

<!-- end list -->

``` r
source("https://raw.githubusercontent.com/jsgosnell/CUNY-BioStats/master/code_examples/bootstrapjsg.R")
bootstrapjsg(drug_b, drug_g)
```

    ## 
    ## Attaching package: 'boot'

    ## The following object is masked from 'package:survival':
    ## 
    ##     aml

    ## Simple Bootstrap Routines (1.1-7)

    ## Warning in boot.ci(a, conf): bootstrap variances needed for studentized
    ## intervals

    ##                                                                       
    ##                             "0.95" "% Percentile Confidence Interval" 
    ##                                                                       
    ##                             "-1.7"               "-0.311904761904762" 
    ##                                                                       
    ##                          "p-value"                           "0.0061"

*Using a bootstrap test with 10000 samples, which is not fully
appropriate here due to small sample sizes, I found a p value of 0.0047.
This p-value is \<.05, so I reject the null hypothesis that the mean
clotting times are the same for the two drugs.*

2.  Data on plant heights (in cm) for plants grown with a new and old
    formulation of fertilizer can be found at
    <https://raw.githubusercontent.com/jsgosnell/CUNY-BioStats/master/datasets/fertilizer.csv>
    . Use the data to test the hypothesis that there is no difference in
    mean plant heights for the two groups

<!-- end list -->

  - Estimating the variance from the data

<!-- end list -->

``` r
fertilizer <- read.csv("https://raw.githubusercontent.com/jsgosnell/CUNY-BioStats/master/datasets/fertilizer.csv")
t.test(height ~ fertilizer, fertilizer)
```

    ## 
    ##  Welch Two Sample t-test
    ## 
    ## data:  height by fertilizer
    ## t = 3.013, df = 15.559, p-value = 0.008458
    ## alternative hypothesis: true difference in means is not equal to 0
    ## 95 percent confidence interval:
    ##  1.367809 7.912191
    ## sample estimates:
    ## mean in group new mean in group old 
    ##             56.55             51.91

*Using a un-paired t-test, since the experimental units were not matched
and I assumed the means of each group would follow a normal distribution
of unknown variance, I found a test statistics of
t<sub>15.559</sub>=3.01. This corresponds to a p-value of 0.008. This
p-value is \<.05, so I to reject the null hypothesis that the impact on
plant growth doesn not differ between the two fertilizer formulations.*

  - Using rank transform analysis

<!-- end list -->

``` r
wilcox.test(height ~ fertilizer, fertilizer)
```

    ## 
    ##  Wilcoxon rank sum exact test
    ## 
    ## data:  height by fertilizer
    ## W = 68, p-value = 0.01166
    ## alternative hypothesis: true location shift is not equal to 0

*Using a un-paired rank-based test, which is appropriate when normality
assumptions can’t be met and I assumed the means of each group would
follow a similar distribution, I found a test statistics of W=68. This
corresponds to a p-value of 0.012. This p-value is \<.05, so I to reject
the null hypothesis that the impact on plant growth doesn not differ
between the two fertilizer formulations.*

  - Using a permutation test

<!-- end list -->

``` r
independence_test(height ~ factor(fertilizer), fertilizer)
```

    ## 
    ##  Asymptotic General Independence Test
    ## 
    ## data:  height by factor(fertilizer) (new, old)
    ## Z = 2.4677, p-value = 0.0136
    ## alternative hypothesis: two.sided

*Using a permutation test, which is appropriate given the sample sizes
and fact I assume similar distributions for each group, I found a test
statistics of Z=2.47. his corresponds to a p-value of 0.01. This p-value
is \<.05, so I to reject the null hypothesis that the impact on plant
growth doesn not differ between the two fertilizer formulations.*

  - Using a bootstrap test

*This is where you may need the different (wide) format of data\! As
always, multiple options exist in R*

``` r
require(reshape2)
```

    ## Loading required package: reshape2

``` r
fertilizer$ID <- 1:nrow(fertilizer)
fertilizer_wide <- dcast(fertilizer, ID~fertilizer, value.var = "height")
#subsetting the long-form data
bootstrapjsg(fertilizer[fertilizer$fertilizer =="old", "height"],
              fertilizer[fertilizer$fertilizer =="new", "height"])
```

    ## Warning in boot.ci(a, conf): bootstrap variances needed for studentized
    ## intervals

    ##                                                                       
    ##                             "0.95" "% Percentile Confidence Interval" 
    ##                                                                       
    ##                "-7.47974959166054"                            "-1.85" 
    ##                                                                       
    ##                          "p-value"                           "0.0018"

``` r
#is same as using the wide data
bootstrapjsg(fertilizer_wide$new, fertilizer_wide$old)
```

    ## Warning in boot.ci(a, conf): bootstrap variances needed for studentized
    ## intervals

    ##                                                                       
    ##                             "0.95" "% Percentile Confidence Interval" 
    ##                                                                       
    ##                 "1.83256260208486"                 "7.44474959166055" 
    ##                                                                       
    ##                          "p-value"                            "7e-04"

*Using a bootstrap test with 10000 samples, I found a p value of 0.013.
This p-value is \<.05, so I to reject the null hypothesis that the
impact on plant growth doesn not differ between the two fertilizer
formulations.*

Note you may need to cast this dataframe into a dataframe with a column
for old and new outcomes. You’ll have to add a unique identifier. Try
something like

``` r
fertilizer$ID <- 1:nrow(fertilizer)
fertilizer_wide <- dcast(fertilizer, ID~fertilizer, value.var = "height")
```

3.  Metabolic rates were measured in animals before and after
    administering a drug. Data is available at

<https://raw.githubusercontent.com/jsgosnell/CUNY-BioStats/master/datasets/metabolic_rates.csv>

Test the hypothesis that the drug has no effect on metabolic rate with
using \* a Student’s t test

``` r
metabolic <- read.csv("https://raw.githubusercontent.com/jsgosnell/CUNY-BioStats/master/datasets/metabolic_rates.csv")
t.test(metabolic$before, metabolic$after, paired = T)
```

    ## 
    ##  Paired t-test
    ## 
    ## data:  metabolic$before and metabolic$after
    ## t = -3.3875, df = 8, p-value = 0.009536
    ## alternative hypothesis: true difference in means is not equal to 0
    ## 95 percent confidence interval:
    ##  -19.982241  -3.795537
    ## sample estimates:
    ## mean of the differences 
    ##               -11.88889

*I used a paired t-test because the same animals were measured before
and after the drug was administered. I also assumed the difference in
means was normally distributed given the trait and sample size. The test
resulted in a statistic of t<sub>8</sub> = -3.39. This corresponds to a
p-value of \<.001. Since the p-value is \<.05, I reject the null
hypothesis that the drug has no effect on metabolic rate.*

  - a rank test

<!-- end list -->

``` r
wilcox.test(metabolic$before, metabolic$after, paired = T)
```

    ## Warning in wilcox.test.default(metabolic$before, metabolic$after, paired = T):
    ## cannot compute exact p-value with ties

    ## 
    ##  Wilcoxon signed rank test with continuity correction
    ## 
    ## data:  metabolic$before and metabolic$after
    ## V = 3, p-value = 0.02427
    ## alternative hypothesis: true location shift is not equal to 0

*I used a paired rank-based test because the same animals were measured
before and after the drug was administered. I did not assume the
difference in means was normally distributed but did assume it followed
a symmetic distribution. The test resulted in a statistic of V = 3. This
corresponds to a p-value of .02. Since the p-value is \<.05, I reject
the null hypothesis that the drug has no effect on metabolic rate.*

  - a binary test

<!-- end list -->

``` r
library(BSDA)
```

    ## Loading required package: lattice

    ## 
    ## Attaching package: 'lattice'

    ## The following object is masked from 'package:boot':
    ## 
    ##     melanoma

    ## 
    ## Attaching package: 'BSDA'

    ## The following object is masked from 'package:datasets':
    ## 
    ##     Orange

``` r
SIGN.test(metabolic$before, metabolic$after)
```

    ## 
    ##  Dependent-samples Sign-Test
    ## 
    ## data:  metabolic$before and metabolic$after
    ## S = 2, p-value = 0.1797
    ## alternative hypothesis: true median difference is not equal to 0
    ## 95 percent confidence interval:
    ##  -24.6111111   0.6111111
    ## sample estimates:
    ## median of x-y 
    ##           -10 
    ## 
    ## Achieved and Interpolated Confidence Intervals: 
    ## 
    ##                   Conf.Level   L.E.pt  U.E.pt
    ## Lower Achieved CI     0.8203 -20.0000 -4.0000
    ## Interpolated CI       0.9500 -24.6111  0.6111
    ## Upper Achieved CI     0.9609 -25.0000  1.0000

*I used a sign test (always paired\!) because the same animals were
measured before and after the drug was administered. I did not assume
the difference in means was normally distributed or that the differences
followed a symmetic distribution. The test resulted in a statistic of s
= 2. This corresponds to a p-value of .18. Since the p-value is \>.05, I
fail to reject the null hypothesis that the drug has no effect on
metabolic rate.*

  - bootstrapping

<!-- end list -->

``` r
bootstrapjsg(metabolic$before - metabolic$after)
```

    ## Warning in boot.ci(a, conf): bootstrap variances needed for studentized
    ## intervals

    ##                                                                         
    ##                  "0.95" "% Confidence Interval"     "-18.3333333333333" 
    ##                                                                         
    ##     "-5.55555555555556"               "p-value"                 "2e-04"

*Since the same animals were measured before and after the drug was
administered, I used a bootstrap (10,000 samples) focused on the
difference in rates. This resulted in a p-value of \<.001. Since the
p-value is \<.05, I reject the null hypothesis that the drug has no
effect on metabolic rate.*

4.  Endurance of the above animals was also measured. Data is available
    at

<https://raw.githubusercontent.com/jsgosnell/CUNY-BioStats/master/datasets/endurance.csv>

Test the hypothesis that the drug has no effect on using \* a Student’s
t test

``` r
endurance <- read.csv("https://raw.githubusercontent.com/jsgosnell/CUNY-BioStats/master/datasets/endurance.csv")
head(endurance)
```

    ##   Subject   time endurance
    ## 1       A before        28
    ## 2       B before        34
    ## 3       C before        30
    ## 4       D before        27
    ## 5       E before        32
    ## 6       F before        38

``` r
t.test(endurance ~ time, endurance, paired = T)
```

    ## 
    ##  Paired t-test
    ## 
    ## data:  endurance by time
    ## t = -1.1195, df = 8, p-value = 0.2954
    ## alternative hypothesis: true difference in means is not equal to 0
    ## 95 percent confidence interval:
    ##  -15.639650   5.417428
    ## sample estimates:
    ## mean of the differences 
    ##               -5.111111

``` r
#or
t.test(endurance[endurance$time == "before", "endurance"],
       endurance[endurance$time == "after", "endurance"],
       paired = T)
```

    ## 
    ##  Paired t-test
    ## 
    ## data:  endurance[endurance$time == "before", "endurance"] and endurance[endurance$time == "after", "endurance"]
    ## t = 1.1195, df = 8, p-value = 0.2954
    ## alternative hypothesis: true difference in means is not equal to 0
    ## 95 percent confidence interval:
    ##  -5.417428 15.639650
    ## sample estimates:
    ## mean of the differences 
    ##                5.111111

*I used a paired t-test because the same animals were measured before
and after the drug was administered. I also assumed the difference in
means was normally distributed given the trait and sample size. The test
resulted in a statistic of t<sub>8</sub> = -3.39. This corresponds to a
p-value of .29. Since the p-value is \>.05, I fail to reject the null
hypothesis that the drug has no effect on metabolic rate.* \* a rank
test

``` r
wilcox.test(endurance ~ time, endurance, paired = T)
```

    ## 
    ##  Wilcoxon signed rank exact test
    ## 
    ## data:  endurance by time
    ## V = 13, p-value = 0.3008
    ## alternative hypothesis: true location shift is not equal to 0

*I used a paired rank-based test because the same animals were measured
before and after the drug was administered. I did not assume the
difference in means was normally distributed but did assume it followed
a symmetic distribution. The test resulted in a statistic of V = 13.
This corresponds to a p-value of .30. Since the p-value is \>.05, I fail
to reject the null hypothesis that the drug has no effect on metabolic
rate.*

  - a binary test

<!-- end list -->

``` r
SIGN.test(endurance[endurance$time == "before", "endurance"],
          endurance[endurance$time == "after", "endurance"])
```

    ## 
    ##  Dependent-samples Sign-Test
    ## 
    ## data:  endurance[endurance$time == "before", "endurance"] and endurance[endurance$time == "after", "endurance"]
    ## S = 7, p-value = 0.1797
    ## alternative hypothesis: true median difference is not equal to 0
    ## 95 percent confidence interval:
    ##  -4.455556 17.766667
    ## sample estimates:
    ## median of x-y 
    ##             4 
    ## 
    ## Achieved and Interpolated Confidence Intervals: 
    ## 
    ##                   Conf.Level  L.E.pt  U.E.pt
    ## Lower Achieved CI     0.8203  2.0000 15.0000
    ## Interpolated CI       0.9500 -4.4556 17.7667
    ## Upper Achieved CI     0.9609 -5.0000 18.0000

*I used a sign test (always paired\!) because the same animals were
measured before and after the drug was administered. I did not assume
the difference in means was normally distributed or that the differences
followed a symmetric distribution. The test resulted in a statistic of s
= 7. This corresponds to a p-value of .17. Since the p-value is \>.05, I
fail to reject the null hypothesis that the drug has no effect on
metabolic rate.*

  - bootstrapping

<!-- end list -->

``` r
bootstrapjsg(endurance[endurance$time == "before", "endurance"]-
             endurance[endurance$time == "after", "endurance"])
```

    ## Warning in boot.ci(a, conf): bootstrap variances needed for studentized
    ## intervals

    ##                                                                         
    ##                  "0.95" "% Confidence Interval"     "-4.11111111111111" 
    ##                                                                         
    ##      "12.8888888888889"               "p-value"                "0.2358"

*Since the same animals were measured before and after the drug was
administered, I used a bootstrap (10,000 samples) focused on the
difference in rates. This resulted in a p-value of 0.23. Since the
p-value is \>.05, I fail to reject the null hypothesis that the drug has
no effect on metabolic rate.*

## For the following problems, make sure you can justify the test you choose to use and carry it out

5.  Using data from Australian athletes
    (<http://www.statsci.org/data/oz/ais.html> for details), determine
    if the average male training at the Australian Institute of Sport
    differs in from the average female training at the site in mercury
    concentration (Hg).

<!-- end list -->

``` r
sport <- sport <- read.table("http://www.statsci.org/data/oz/ais.txt", header = T)
t.test(Hg ~ Sex, sport)
```

    ## 
    ##  Welch Two Sample t-test
    ## 
    ## data:  Hg by Sex
    ## t = -15.248, df = 199.99, p-value < 2.2e-16
    ## alternative hypothesis: true difference in means is not equal to 0
    ## 95 percent confidence interval:
    ##  -2.250666 -1.735216
    ## sample estimates:
    ## mean in group female   mean in group male 
    ##             13.56000             15.55294

*I used a t-test (not paired) since mercury concentration can be assumed
to follow a normal distribution at this sample size. This resulted in a
test statistic of t<sub>199.99</sub> = -15.25, with a corresponding
p-value of \<.001. Since this p-value is \<.05, I reject the null
hypothesis that there is no difference in average mercury concentration
between males and females. If I wanted to graph this, I might use*

``` r
library(ggplot2)
ggplot(sport, aes_string("Hg"))+
  geom_histogram() +
  facet_wrap(~Sex) +
  ggtitle(" Plasma ferritin concentration \n of Australian athletes") +
  xlab("Ferritin concentration")+
  theme(axis.title.x = element_text(face="bold", size=28), 
        axis.title.y = element_text(face="bold", size=28), 
        axis.text.y  = element_text(size=20),
        axis.text.x  = element_text(size=20), 
        legend.text =element_text(size=20),
        legend.title = element_text(size=20, face="bold"),
        plot.title = element_text(hjust = 0.5, face="bold", size=32),
        strip.text.x = element_text(size = 22))
```

    ## `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.

![](6._Continuous_tests_for_2_populations_answers_files/figure-gfm/unnamed-chunk-19-1.png)<!-- -->

*which suggests males tend to have a higher Hg concentration.*

6.  Laureysens et al. (2004) measured metal content in the wood of 13
    poplar clones growing in a polluted area, once in August and once in
    November. Concentrations of aluminum (in micrograms of Al per gram
    of wood) are shown below. (From Handbook of Biological Statistics).
    Has metal content changed over time?

| Clone          | August | November |
| -------------- | ------ | -------- |
| Columbia River | 18.3   | 12.7     |
| Fritiz Pauley  | 13.3   | 11.1     |
| Hazendas       | 16.5   | 15.3     |
| Primo          | 12.6   | 12.7     |
| Raspalje       | 9.5    | 10.5     |
| Hoogvorst      | 13.6   | 15.6     |
| Balsam Spire   | 8.1    | 11.2     |
| Gibecq         | 8.9    | 14.2     |
| Beaupre        | 10.0   | 16.3     |
| Unal           | 8.3    | 15.5     |
| Trichobel      | 7.9    | 19.9     |
| Gaver          | 8.1    | 20.4     |
| Wolterson      | 13.4   | 36.8     |

``` r
poplar <- read.table("https://raw.githubusercontent.com/jsgosnell/CUNY-BioStats/master/datasets/poplar.csv",
                   stringsAsFactors = T, header = T)
poplar$difference <- poplar$November - poplar$August

#plot to consider distribution
ggplot(poplar, aes_string("difference"))+
  geom_histogram() +
  theme(axis.title.x = element_text(face="bold", size=28), 
        axis.title.y = element_text(face="bold", size=28), 
        axis.text.y  = element_text(size=20),
        axis.text.x  = element_text(size=20), 
        legend.text =element_text(size=20),
        legend.title = element_text(size=20, face="bold"),
        plot.title = element_text(hjust = 0.5, face="bold", size=32),
        strip.text.x = element_text(size = 22))
```

    ## `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.

![](6._Continuous_tests_for_2_populations_answers_files/figure-gfm/unnamed-chunk-20-1.png)<!-- -->

``` r
#lots of holes, but fairly symmetric
wilcox.test(poplar$August, poplar$November, paired=TRUE)
```

    ## 
    ##  Wilcoxon signed rank exact test
    ## 
    ## data:  poplar$August and poplar$November
    ## V = 16, p-value = 0.03979
    ## alternative hypothesis: true location shift is not equal to 0

``` r
#also could do
bootstrapjsg(poplar$difference)
```

    ## Warning in boot.ci(a, conf): bootstrap variances needed for studentized
    ## intervals

    ##                                                                         
    ##                  "0.95" "% Confidence Interval"      "1.24615384615385" 
    ##                                                                         
    ##      "9.23076923076923"               "p-value"                "0.0154"

*I plotted the paired data to consider its distribution. Given its shape
and a lack of knowledge regarding metal concentration distribution, I
used a rank-based test for paired data. This led to a statistic of V =
17 and p-value of 0.04. Since this is \< .05, I reject the null
hypothesis that average metal concentration did not differ between the
two measurements. Similar results were reached used a bootstrapping
approach.*

7.  Data was collected on cholesterol levels following heart attacks.
    Data available at <http://www.statsci.org/data/general/cholestg.txt>

Note to read a .txt file you use,
read.table(“<http://www.statsci.org/data/general/cholestg.txt>”,
header = T, stringsAsFactors = T) Check the defaults to understand the
argument.  
More info on the data is @
<http://www.statsci.org/data/general/cholest.html> Is there evidence
cholesterol levels changed between day 2 and day 14?  
**THINK ABOUT RELABELLING DAY AS A FACTOR (WHY?)?**

``` r
cholesterol <- read.table("http://www.statsci.org/data/general/cholestg.txt", header = T)
cholesterol$day <- as.factor(cholesterol$day)
head(cholesterol)
```

    ##   patient group day cholest
    ## 1       1     1   2     270
    ## 2       2     1   2     236
    ## 3       3     1   2     210
    ## 4       4     1   2     142
    ## 5       5     1   2     280
    ## 6       6     1   2     272

``` r
summary(cholesterol)
```

    ##     patient          group         day        cholest     
    ##  Min.   : 1.00   Min.   :1.000   2   :28   Min.   :116.0  
    ##  1st Qu.:10.00   1st Qu.:1.000   4   :28   1st Qu.:188.0  
    ##  Median :19.50   Median :1.000   14  :28   Median :220.0  
    ##  Mean   :22.13   Mean   :1.263   NA's:30   Mean   :224.5  
    ##  3rd Qu.:29.75   3rd Qu.:2.000             3rd Qu.:256.0  
    ##  Max.   :58.00   Max.   :2.000             Max.   :360.0  
    ##                                            NA's   :9

``` r
ggplot(cholesterol[cholesterol$day %in% c("2", "14"),], aes_string("cholest")) +
  geom_histogram() +
  theme(axis.title.x = element_text(face="bold", size=28), 
        axis.title.y = element_text(face="bold", size=28), 
        axis.text.y  = element_text(size=20),
        axis.text.x  = element_text(size=20), 
        legend.text =element_text(size=20),
        legend.title = element_text(size=20, face="bold"),
        plot.title = element_text(hjust = 0.5, face="bold", size=32))+
  facet_wrap(~day)
```

    ## `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.

    ## Warning: Removed 9 rows containing non-finite values (stat_bin).

![](6._Continuous_tests_for_2_populations_answers_files/figure-gfm/unnamed-chunk-21-1.png)<!-- -->

``` r
t.test(cholesterol[cholesterol$day == "2", "cholest"], 
       cholesterol[cholesterol$day == "14", "cholest"],
       paired = T)
```

    ## 
    ##  Paired t-test
    ## 
    ## data:  cholesterol[cholesterol$day == "2", "cholest"] and cholesterol[cholesterol$day == "14", "cholest"]
    ## t = 3.2883, df = 18, p-value = 0.004085
    ## alternative hypothesis: true difference in means is not equal to 0
    ## 95 percent confidence interval:
    ##  13.7215 62.2785
    ## sample estimates:
    ## mean of the differences 
    ##                      38
